"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { ClerkProvider } from "@clerk/nextjs";
const inter = Inter({ subsets: ["latin"] });
import { CartContext } from "./_context/CartContext.js";
import { useEffect, useState } from "react";

export default function RootLayout({ children }) {
  const [metadata, setMetadata] = useState({
    title: "CODE〰️BRO",
    description: "Generated by CODE-BRO TEAM",
    icons: {
      icon: ["/favicon.ico?v=4"],
      apple: ["/apple-touch-icon.png?v=4"],
      shortcut: ["/apple-touch-icon.png"],
    },
    manifest: "/site.webmanifest",
  });

  useEffect(() => {
    // Update document title and other metadata
    document.title = metadata.title;
    const metaDescription = document.querySelector('meta[name="description"]');
    if (metaDescription) {
      metaDescription.setAttribute("content", metadata.description);
    }

    const linkIcon = document.querySelector('link[rel="icon"]');
    if (linkIcon) {
      linkIcon.setAttribute("href", metadata.icons.icon[0]);
    }

    const linkAppleIcon = document.querySelector(
      'link[rel="apple-touch-icon"]'
    );
    if (linkAppleIcon) {
      linkAppleIcon.setAttribute("href", metadata.icons.apple[0]);
    }

    const linkManifest = document.querySelector('link[rel="manifest"]');
    if (linkManifest) {
      linkManifest.setAttribute("href", metadata.manifest);
    }
  }, [metadata]);

  const [cart, setCart] = useState([]);

  return (
    <ClerkProvider>
      <CartContext.Provider value={{ cart, setCart }}>
        <html lang="en">
          <body className={inter.className}>
            <Header />
            {children}
            <Footer />
          </body>
        </html>
      </CartContext.Provider>
    </ClerkProvider>
  );
}
